version: '3.8'

services:

  ce_traefik:
    image: "traefik:v2.2"
    container_name: "ce_traefik"
    restart: unless-stopped
    command:
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=true"
        - "--api.insecure=true"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.web.forwardedheaders.insecure"
        - "--entrypoints.web.proxyprotocol.insecure"
    ports:
        - 80:80
    volumes: 
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks: 
        - ce_network

  ce_db:
    container_name: "ce_db"
    image: "postgres:12-alpine"
    restart: unless-stopped
    volumes:
      - ce_db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=ce_user
      - POSTGRES_PASSWORD=PasswordHere123
      - POSTGRES_DB=collection_editor
    networks:
      - ce_network

  ce_mongo:
    container_name: "ce_mongo"
    image: "mongo:4.2"
    restart: unless-stopped
    volumes:
      - init_db:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=collection_editor
      - MONGO_INITDB_ROOT_USERNAME=ce_user
      - MONGO_INITDB_ROOT_PASSWORD=PasswordHere123
    networks:
      - ce_network

  ce_backend:
    container_name: "ce_backend"
    image: "registry.gitlab.whiteaster.com/openforestdata/backend/collection-editor:latest"
    restart: unless-stopped
    environment:
        - DEBUG=True
        - DB_NAME=collection_editor
        - DB_HOST=ce_db
        - DB_ENGINE=postgres
        - DB_DATABASE=collection_editor
        - DB_USER=ce_user
        - DB_PASSWORD=PasswordHere123
        - MONGO_HOST=ce_mongo
        - MONGO_DATABASE=collection_editor
        - MONGO_USER=ce_user
        - MONGO_PASSWORD=PasswordHere123
        - LDAP_HOST='ldap://ldap_host_here'
        - LDAP_USERNAME='cn=username,ou=ldap,dc=here,dc=local'
        - LDAP_PASSWORD='PasswordHere123'
        - LDAP_SEARCH_HOST='ou=search,ou=host,dc=here'
        - LDAP_FORMAT='sAMAccountName'
        - DATAVERSE_URL=https://data-epuszcza.biaman.pl
        - DATAVERSE_ACCESS_TOKEN=dataverse_access_token_here
        - SECRET_KEY=SECRET_KEY_token_here
    volumes: 
        - ce_backend_static:/app/static/
    labels:
        - traefik.enable=true
        - traefik.http.routers.ce_backend.rule=Host(`${URL}`) && PathPrefix (`/api`)
        - traefik.http.services.ce_backend.loadbalancer.server.port=8000
        - traefik.http.routers.ce_backend.entrypoints=web
        - traefik.http.middlewares.ce_backend.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH
        - traefik.http.middlewares.ce_backend.headers.accesscontrolalloworigin=origin-list-or-null
        - traefik.http.middlewares.ce_backend.headers.accesscontrolmaxage=100
        - traefik.http.middlewares.ce_backend.headers.addvaryheader=true
    networks:
      - ce_network

  ce_frontend:
    container_name: "ce_frontend"
    image: "registry.gitlab.whiteaster.com/openforestdata/frontend/collection-editor-frontend:latest"
    restart: unless-stopped
    environment:
      - PROD=true
      - HOSTNAME=${http}://${URL}/api/
    volumes: 
      - ce_backend_static:/static/
    labels:
      - traefik.enable=true
      - traefik.http.routers.ofd_agregator_frontend.rule=Host(`${URL}`)
      - traefik.http.services.ofd_agregator_frontend.loadbalancer.server.port=80
      - traefik.http.routers.ofd_agregator_frontend.entrypoints=web
      - traefik.http.middlewares.ofd_agregator_frontend.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH
      - traefik.http.middlewares.ofd_agregator_frontend.headers.accesscontrolalloworigin=origin-list-or-null
      - traefik.http.middlewares.ofd_agregator_frontend.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.ofd_agregator_frontend.headers.addvaryheader=true
    networks:
      - ce_network

# volumes definiton
volumes:
  init_db:
  ce_db:
  mongo_data:
  ce_network:
  ce_backend_static:

# network definition
networks:
  ce_network:
    driver: bridge